fix: install missing library
g4s8/pdd-action pull request #4
Opened 2022-02-03 16:21 UTC by baudoliver7

We install package `xz-libs` to make shared library `liblzma.so.5` available.

2022-02-03 16:24 UTC, baudoliver7 commented
@g4s8 I tested it on my fork. See [this PR](https://github.com/my-supervisor/my-supervisor/pull/45).

2022-02-04 10:16 UTC, g4s8 requested changes
@baudoliver7 thanks! please check my comments

2022-02-04 10:16 UTC, g4s8 commented on .gitattributes
> +*.png binary
There are no java xml or png files here

2022-02-04 10:16 UTC, g4s8 commented on Dockerfile
> +  apk add --update --no-cache ruby && \
You can just specify multiple targets for `add` in one command:
```suggestion
RUN apk add --update --no-cache ruby xz-libs && \
```

2022-02-04 10:27 UTC, baudoliver7 commented
@g4s8 fixed (see latest commit).

2022-02-04 10:27 UTC, g4s8 approved these changes
@baudoliver7 thanks a lot!

2022-02-04 10:27 UTC, merged